name: "Stale issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *"  # Runs everyday at 00:00 UTC
  workflow_dispatch:     # Allows for manual run

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          # Issues settings
          days-before-issue-stale: 30
          days-before-issue-close: 7
          stale-issue-label: "stale"
          exempt-issue-labels: "important,security"
          stale-issue-message: |
            Hi there! 👋 This issue hasn't seen any activity lately.
            We're marking it as stale to help us keep track of what's
            currently being worked on. If you still think this needs
            attention, just drop a comment and we’ll keep it alive!
            Otherwise it'll be closed after 7 days.
          close-issue-message: |
            Sorry to say, but we've to close this issue because there hasn't
            been any activity after it was marked stale. Again if you
            still think this needs attention, reopen the issue and we'll
            keep it alive!

          # PRs settings
          days-before-pr-stale: 45
          days-before-pr-close: -1
          stale-pr-label: "stale"
          exempt-pr-labels: "important,security,wip"
          stale-pr-message: |
            Hi there! 👋 This PR hasn't seen any activity lately.
            We're marking it as stale to help us keep track of what's
            currently being worked on. If you still think this needs
            attention, just drop a comment and we’ll keep it alive!
            We know you have worked on this, so we're not going to
            close it."
