name: "Test C++ Compatibility Check Action"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pre-commit-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Test C++ Compatibility Check Action
        uses: thedevmystic/github-actions/cpp-compatibility-check@main
        with:
          os: "linux"
          compiler: "g++"
          cmake-location: "./.github/dummy-cpp-project/"
